# Generated by Django 5.1.6 on 2025-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_highlight_asset',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_post_asset',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='page_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
