# Generated by Django 5.1.6 on 2025-12-02 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_extraservice_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='designer_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='editor_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='social_admin_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='videographer_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='writer_user',
        ),
        migrations.AddField(
            model_name='project',
            name='designers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'designer'}, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='تیم گرافیک'),
        ),
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editor_projects', to=settings.AUTH_USER_MODEL, verbose_name='تیم تدوین'),
        ),
        migrations.AddField(
            model_name='project',
            name='social_admins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'social_admin'}, related_name='social_projects', to=settings.AUTH_USER_MODEL, verbose_name='تیم ادمین سوشال'),
        ),
        migrations.AddField(
            model_name='project',
            name='videographers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'videographer'}, related_name='videographer_projects', to=settings.AUTH_USER_MODEL, verbose_name='تیم فیلم\u200cبرداری'),
        ),
        migrations.AddField(
            model_name='project',
            name='writers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'writer'}, related_name='writer_projects', to=settings.AUTH_USER_MODEL, verbose_name='تیم نویسندگان'),
        ),
    ]
