# Generated by Django 5.1.6 on 2025-11-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.BigIntegerField(default=0, help_text='مبلغ کل قرارداد به تومان'),
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
        ),
    ]
