# Generated by Django 5.1.6 on 2025-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='agency_files/', verbose_name='فایل')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
        ),
    ]
