# Generated by Django 5.1.6 on 2025-11-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_contract_amount_projectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.CharField(choices=[('method1', 'روش اول (۳۰-۳۰-۴۰)'), ('method2', 'روش دوم (۵۰-۵۰)'), ('method3', 'روش سوم (۱۰۰٪ نقد - ۱۵٪ تخفیف)')], default='method1', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_package',
            field=models.CharField(choices=[('pkg1', 'پکیج اول (۳۰ میلیون)'), ('pkg2', 'پکیج دوم (۲۲ میلیون)'), ('pkg3', 'پکیج سوم (۱۵ میلیون)'), ('pkg4', 'پکیج چهارم (۹ میلیون)')], default='pkg1', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
