# Generated by Django 5.1.6 on 2025-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_agencyfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پرسونای مخاطب')),
                ('icon_name', models.CharField(default='group', max_length=50, verbose_name='نام آیکون')),
                ('age_range', models.CharField(blank=True, max_length=50, verbose_name='بازه سنی')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='جنسیت')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='شغل/سمت')),
                ('income_level', models.CharField(blank=True, max_length=100, verbose_name='سطح درآمد')),
                ('pain_points', models.TextField(blank=True, verbose_name='دغدغه\u200cها و دردها')),
                ('goals', models.TextField(blank=True, verbose_name='اهداف و خواسته\u200cها')),
                ('our_solution', models.TextField(blank=True, verbose_name='راه\u200cحل پیشنهادی ما')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
