# Generated by Django 5.1.6 on 2025-11-22 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designer_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='گرافیست'),
        ),
        migrations.AddField(
            model_name='project',
            name='editor_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_projects', to=settings.AUTH_USER_MODEL, verbose_name='تدوین\u200cگر'),
        ),
        migrations.AddField(
            model_name='project',
            name='social_admin_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'social_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_projects', to=settings.AUTH_USER_MODEL, verbose_name='ادمین پیج'),
        ),
        migrations.AddField(
            model_name='project',
            name='videographer_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'videographer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videographer_projects', to=settings.AUTH_USER_MODEL, verbose_name='فیلم\u200cبردار'),
        ),
        migrations.AddField(
            model_name='project',
            name='writer_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_projects', to=settings.AUTH_USER_MODEL, verbose_name='سناریو نویس'),
        ),
    ]
