# Generated by Django 5.1.6 on 2025-11-23 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_designer_user_project_editor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان هزینه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('expense_type', models.CharField(choices=[('rent', 'اجاره دفتر'), ('utility', 'قبوض (آب، برق، اینترنت)'), ('software', 'خرید اشتراک نرم\u200cافزار/سایت'), ('marketing', 'تبلیغات و بازاریابی'), ('equipment', 'خرید تجهیزات'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی')),
                ('date', models.DateField(verbose_name='تاریخ هزینه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='babat (e.g., salary of Azar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(limit_choices_to=models.Q(('role', 'client'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='پرسنل')),
            ],
        ),
    ]
