# Generated by Django 5.1.6 on 2025-12-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_stickynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
