# Generated by Django 5.1.6 on 2025-11-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_scenariocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='scenario_finals/'),
        ),
    ]
