# Generated by Django 5.1.6 on 2025-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قانون')),
                ('trigger_type', models.CharField(choices=[('project_created', 'هنگام ساخت پروژه جدید'), ('task_done', 'هنگام تکمیل شدن یک تسک')], max_length=50)),
                ('action_type', models.CharField(choices=[('create_default_tasks', 'ایجاد تسک\u200cهای پیش\u200cفرض'), ('notify_client', 'ارسال اعلان به مشتری')], max_length=50)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
