# Generated by Django 5.1.6 on 2025-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_filecomment_guest_name_alter_filecomment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_type',
            field=models.CharField(choices=[('reels', 'ریلز (Reels)'), ('story', 'استوری (Story)')], default='reels', max_length=10, verbose_name='نوع سناریو'),
        ),
    ]
