# Generated by Django 5.1.6 on 2025-11-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
