# Generated by Django 5.1.6 on 2025-12-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_dashboardconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام سرنخ / مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('new', 'تماس اولیه'), ('meeting', 'جلسه حضوری/آنلاین'), ('proposal', 'ارسال پروپوزال'), ('negotiation', 'در حال مذاکره'), ('won', 'برنده شد (قرارداد)'), ('lost', 'از دست رفت')], default='new', max_length=20)),
                ('estimated_value', models.BigIntegerField(default=0, verbose_name='ارزش تخمینی (تومان)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='projects.targetaudience', verbose_name='دسته مخاطب هدف')),
            ],
        ),
    ]
