# Generated by Django 5.1.6 on 2025-11-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_chatmessage_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('pv', 'PV'), ('group', 'Group')], default='pv', max_length=10),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expense_type',
            field=models.CharField(choices=[('rent', 'اجاره'), ('utility', 'قبوض'), ('software', 'نرم\u200cافزار'), ('marketing', 'تبلیغات'), ('other', 'سایر')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
