# Generated by Django 5.1.6 on 2025-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_chatroom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('filming', 'آفیش فیلمبرداری'), ('post', 'تاریخ انتشار پست'), ('meeting', 'جلسه (حضوری/آنلاین)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
