# Generated by Django 6.0 on 2025-12-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_task_priority_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'برای انجام'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], db_index=True, default='todo', max_length=20),
        ),
    ]
