# Generated by Django 5.1.6 on 2025-11-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_calendarevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('instagram', 'مدیریت پیج اینستاگرام'), ('teaser', 'پروژه تکی (تیزر/طراحی/...)')], default='instagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='monthly_post_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='page_password_encrypted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='page_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
