# Generated by Django 6.0 on 2026-02-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_level',
            field=models.IntegerField(default=1, verbose_name='Difficulty Level (1-5)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_extra_mile',
            field=models.BooleanField(default=False, verbose_name='Extra Mile'),
        ),
        migrations.AddField(
            model_name='task',
            name='kpi_points',
            field=models.IntegerField(default=10, verbose_name='KPI Points'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هدف (Objective)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_points', models.IntegerField(default=100, verbose_name='هدف امتیازی (Target KPI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_objectives', to=settings.AUTH_USER_MODEL, verbose_name='مسئولین هدف')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='projects.project')),
            ],
        ),
    ]
