# Generated by Django 6.0 on 2026-02-15 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_rename_due_date_task_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[('project', 'مربوط به پروژه (عادی)'), ('daily', 'وظیفه روزانه (روتین)'), ('weekly', 'وظیفه هفتگی'), ('monthly', 'هدف ماهانه')], default='project', max_length=20, verbose_name='دوره زمانی'),
        ),
        migrations.CreateModel(
            name='PersonnelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('penalty', 'نکات منفی / جریمه'), ('bonus', 'نکات مثبت / پاداش'), ('info', 'گزارش / یادداشت')], max_length=20)),
                ('category', models.CharField(choices=[('discipline', 'انضباطی (تاخیر/غیبت)'), ('financial_loss', 'ضرر مالی به مجموعه'), ('value_add', 'ارزش افزوده / خلاقیت'), ('behavior', 'رفتار سازمانی'), ('speed', 'سرعت عمل')], max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان موضوع')),
                ('description', models.TextField(verbose_name='شرح کامل')),
                ('financial_impact', models.BigIntegerField(default=0, verbose_name='مبلغ تاثیر مالی (تومان)')),
                ('score_impact', models.IntegerField(default=0, verbose_name='تاثیر روی امتیاز KPI')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
