# Generated by Django 5.1.6 on 2025-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کل (Admin)'), ('client', 'مشتری (Client)'), ('writer', 'سناریو نویس'), ('videographer', 'فیلم\u200cبردار'), ('editor', 'تدوین\u200cگر / ادیتور'), ('designer', 'گرافیست (UI/UX)'), ('social_admin', 'ادمین پیج')], default='client', max_length=20),
        ),
    ]
